### ISSUE TITLE
Check Kafka Functionality with FREE_FORM, SEPA and COUNTERPARTY

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#322]
in create transaction request for sepa type and free_form type, save transaction is not called at all, and transaction request remains initialised.

**Comment by marko-md** [comment]
@simonredfern In case that Kafka cannot provide us threshold which rise a challenge request we set default limit of amount to 0. I.e. every transaction request remains initialised and challenge is triggered. To change state to completed of it the challenged has to be answered properly. 
Commit: [Challenge threshold set to 0 instead of 50 in case of bad response from Kafka](https://github.com/OpenBankProject/OBP-API/commit/6d0fd5acad8e017e0e8f7c4e40d83c00b4b8a8e7)

**Comment by simonredfern** [comment]
If challenge is raised (value exceeds challenge limit), we need to check that answering security challenge (via 2_1_0 by answerTransactionRequestChallenge) calls saveTransaction over Kafka.
