### ISSUE TITLE
modify the Update Consumer RedirectUrl endpoint and show the Consumer_ID in Consumer Registration Form

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-API#336]
PUT /management/consumers/CONSUMER_ID/consumer/redirect_url

BODY {"redirect_url":"http://localhost:8888"}

show the Consumer_ID after the developer register the new App

**Comment by fsofronis** [comment]
During our testing activities, identified that the redirectUrl parameter is vulnerable to reflected cross-site scripting (XSS) attacks due to inadequate sanitization of user supplied data.

Vulnerable parameter: 'redirectUrl'
resource: 'http://openbankdev:8080/oauth/thanks'
vector: http://openbankdev:8080/oauth/thanks?redirectUrl=[JS attack vector]

**Comment by hongwei1** [comment]
Hi Fsofronis @fsofronis , We solve the XSS in this ticket.  https://github.com/OpenBankProject/OBP-API/issues/279

**Comment by fsofronis** [comment]
Thnks
