### ISSUE TITLE
Create end point for meetings

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#37]
Create a meeting resource to enable video or other chat (or physical meeting).

This is to support video and other chats during onboarding or other situations

Add to: 
v2.0.0

POST /banks/BANK_ID/meetings

Request

{
	"provider_id": "tokbox",
	"purpose": "ONBOARDING",
	"requested_start_date": "date"
}

Response

{
	"id": "123",
	"provider_id": "tokbox",
	"how": {
		"session_id": "456",
		"token_1": "789",
		"token_2": "1234"
	},
	"with": {
		"bank_id": "123",
		"customer_user_id": "bob",
		"agent_user_id": "jill"
	},
	"purpose": "ONBOARDING",
	"requested_start_date": "date"
}

Session Id and tokens come from tok box

We need server code that calls tokbox (in this case) to get the session and tokens.
https://tokbox.com/developer/rest/ 

GET /banks/BANK_ID/meetings
GET /banks/BANK_ID/meetings/MEETING_ID

**Comment by t0rst** [comment]
token_1 might be better as token_attendee_1, etc.

token_attendee_1 is for the customer, and needs to have the role "publisher"

token_attendee_2 is for the staff member, and needs to have the role "moderator"

It would also be very useful if each token's "Connection data" included at least the OBP user id for that token, e.g. as a JSON formatted string:  {"obp_user_id" : ""}  (Use obp_ prefix to distinguish obp data from tokbox data in the string.)

**Comment by t0rst** [comment]
I don't see the point of "requested_start_date" in the request parameters. In the real world, the chances of having a meeting at exactly the time requested are pretty slim. For the real world there are two possibilities: a) supply no date, implying give me a meeting as soon as possible, b) supply the range of times available, so that the first period overlapping availability of the other parties can be chosen, i.e. "requested_when" would be an array of date pairs. (A sub-optimal version would take just a single pair of "available_from" + "available_to", but this would lead to hunting iterations.)

Option b) is not needed for the onboarding demo, so just omit it.


The reply _must_ have the meeting start time "when" (or "meeting_start_date" or whatever), which is the earliest time when all resources (attendees, meeting room, etc.) are available, and is never guaranteed to be the same as the first instance of one person's availability. It is a different parameter to the time range(s) in the request (the requested times could be repeated in the reply, but that would just be for reference).

For a video meeting requested ASAP, in the real world "when" would be the next-up time passed back from a call centre link, i.e. seconds to minutes away. In the demo world, "when" could be an arbitrary 5 or 10 seconds after the time of the meeting request; although faked in demo mode, "when" is still essential as it serves to show sequence of meetings, shows whether a meeting is passed or yet to occur — all important for queries.

Summary:
- don't bother with "requested_start_date" in the request; we only support the implied ASAP. (Can add "when" later when needs fully analysed and approach decided.)
- need "when" in the reply, set to 5-15 seconds after request received (tweek per experience)

**Comment by simonredfern** [comment]
So: 

POST /banks/BANK_ID/meetings

Request

{
"provider_id": "tokbox",
"purpose": "ONBOARDING"
}

?

**Comment by t0rst** [comment]
That'd do it. 

You could also make it explicitly clear that the parameters in "how" are specific to provider, e.g. inside have "tokbox_session_id" and "tokbox_token_..."

**Comment by marko-md** [comment]
Used setup:

- session set to media router — necessary in order to have video recorded

- token expiry time set to 60 mins for now (tokens are cheap to create and for one-off use, not recurring use)
