### ISSUE TITLE
Metrics. Filters Part 1. Add url string *filtering* (no wilde cards etc.) parameters to GET /management/metrics

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#375]
Should be able to filter on the following metrics fields

 from_start_date (defaults to one week before current date)
 to_start_date (defaults to current date)
 limit (for pagination: defaults to 200)
 offset (for pagination: zero index, defaults to 0)

**Comment by sebtesobe** [comment]
I believe having defaults for the date period is unnecessary. What happens when there have been no entries in the last week? I would see no records. When i go to `/management/metrics` i expect to see all records since the beginning of time, guarded by the default `limit`, though. 

I find `from_start_date` and `to_start_date` as names a bit weird. Wouldn't `from_date` and `to_date` or `start_date` and `end_date` better?
