### ISSUE TITLE
Separate Counterparties by Akka

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#398]

**Comment by hongwei1** [comment]
for Counterparties  #c8e731c
But no CounterpartyTrait yet.  Because :

def getCounterpartyByCounterpartyId(counterpartyId: CounterpartyId): Box[CounterpartyTrait]
def getCounterpartyByIban(iban: String): Box[CounterpartyTrait]

there two methods are belong to " trait Connector ", not belong to "trait Counterparties".
Do we need move all methods from "trait Connector " to Akka?

**Comment by constantine2nd** [comment]
Done.
