### ISSUE TITLE
Create Customer via Staff User

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#46]
POST to customer but specify the customer_user_id in the JSON Body instead of using the logged in user_id

**Comment by simonredfern** [comment]
Actually this call doesn't even need to link to the User. 
That step can be done with POST /user_customer_links

**Comment by marko-md** [comment]
There are two end points:

1. v1.4.0, addCustomer, POST /banks/BANK_ID/customer
In this end point we use logged user

2. v2.0.0, createCustomer, POST /banks/BANK_ID/customers
In this end point we use user_id from posted JSON in order to find a specific user
customer_user <- User.findByUserId(postedData.user_id) ?~! ErrorMessages.UserNotFoundById

@simonredfern are we talking about first or second end point?

**Comment by simonredfern** [comment]
I'm talking about the v2.0.0 endpoint. But we shouldn't break existing functionality. 

So if the POSTed user_id is null then it should just create a customer.

**Comment by simonredfern** [comment]
https://apiexplorersandbox.openbankproject.com/#2_0_0-createCustomer

**Comment by simonredfern** [comment]
We need to add canCreateCustomer Role and end point should check for that role.
