### ISSUE TITLE
PSD2 API clarification... and some more!

### ISSUE THREAD

**Issue by gbrault** [OpenBankProject/OBP-API#847]
1- Could you guide me about "why" you selected the set of interfaces we have today in OBP PSD2? I can see they are evolutions between v2.0.0 to v3.0.0 (12 to 18 endpoints) do you have a roadmap link available for the future of PSD2?
1.5- even if the /users/current is not showing up in the PSD2 API browser, it works (I can call it after direct auth like in the full OBP API): is it normal or is it a bug?
2- I have a question about Counterparties: will it be possible to set some counterparties information upfront for a given account, or do we have to make a Transaction for that?
3- Do you plan to organize some place about user manuals and typical development use cases?
4- Thx for all the work you have done guys!

**Comment by simonredfern** [comment]
Hi @gbrault 


Re 1) In API Explorer, "PSD2" acts a filter on the resource docs (which describe the endpoints). It is possible to disable endpoints (in the Props file) and thus resource docs displayed. But the PSD2 link is just a filter. So its normal. We selected that set because they cover the core requirements of PSD2 (access to accounts, payments and related). By the way we just introduced a "spelling" parameter so that json keys can are named with ISO20022 names e.g. "Ccy" instead of "Currency". 

Re 1.5 If you want to disable endpoints, use the Props file on your own installation.  

Re 2, Yes you can create counterparties up front. In fact now, for transaction request type = SEPA and COUNTERPARTY you must do this.  

Re 3, Could come with commercial support for sure. Else, when we can! We (TESOBE) generally publish diagrams etc pretty fast but of course there is some knowledge / effor that clients money buys ;-)

Re 4, Welcome. Hope you can make good use of it.

Feel free to use our slack channels for general questions (sign up here https://slack.openbankproject.com/ )

cheers,
Simon
